USE JJOO;

INSERT INTO Deportes (Nombre, Foto, Banner)
VALUES
    ('Atletismo', 'https://olympics.com/images/static/sports/pictograms/v2/ath.svg', 'https://img.olympics.com/images/image/private/t_s_pog_staticContent_hero_xl_2x/f_auto/primary/ntg4t1lytzt11bzbnkqv'),
    ('Bádminton', 'https://olympics.com/images/static/sports/pictograms/v2/bdm.svg', 'https://img.olympicchannel.com/images/image/private/t_16-9_1920/f_auto/primary/xzavgkfd2bvdqvblxnrh'),
    ('Baloncesto', 'https://olympics.com/images/static/sports/pictograms/v2/bkb.svg', 'https://img.olympicchannel.com/images/image/private/t_16-9_1920/f_auto/primary/jnefp96qvymodu9lflih'),
    ('Baloncesto 3x3', 'https://olympics.com/images/static/sports/pictograms/v2/bk3.svg', 'https://img.olympics.com/images/image/private/t_s_pog_staticContent_hero_xl_2x/f_auto/primary/gxdey9da0ibkxftyuplz'),
    ('Balonmano', 'https://olympics.com/images/static/sports/pictograms/v2/hbl.svg', 'https://img.olympics.com/images/image/private/t_s_pog_staticContent_hero_xl_2x/f_auto/v1710759171/primary/q3xjezyajduuey64plmw'),
    ('Boxeo', 'https://olympics.com/images/static/sports/pictograms/v2/box.svg', 'https://img.olympics.com/images/image/private/t_s_pog_staticContent_hero_lg_2x/f_auto/primary/zk1emf45sohwctce0hhg'),
    ('Breaking', 'https://olympics.com/images/static/sports/pictograms/v2/bkg.svg', 'https://img.olympicchannel.com/images/image/private/t_16-9_1920/f_auto/primary/g7hwbrz64sye32vcvehd'),
    ('Ciclismo BMX Freestyle', 'https://olympics.com/images/static/sports/pictograms/v2/bmf.svg', 'https://img.olympicchannel.com/images/image/private/t_16-9_1920/f_auto/primary/sco18jtjksyhec0m8mbh'),
    ('Ciclismo BMX Racing', 'https://olympics.com/images/static/sports/pictograms/v2/bmx.svg', 'https://img.olympicchannel.com/images/image/private/t_16-9_1920/f_auto/primary/kruwzynhrkfkhaqwfxe4'),
    ('Ciclismo de montaña', 'https://olympics.com/images/static/sports/pictograms/v2/mtb.svg', 'https://img.olympicchannel.com/images/image/private/t_16-9_1920/f_auto/primary/wrqeruvyhs4k6ajzntyz'),
    ('Ciclismo en pista', 'https://olympics.com/images/static/sports/pictograms/v2/ctr.svg', 'https://img.olympics.com/images/image/private/t_s_pog_staticContent_hero_xl_2x/f_auto/v1668679688/primary/uyynza5tmypufqqve330'),
    ('Ciclismo en ruta', 'https://olympics.com/images/static/sports/pictograms/v2/crd.svg', 'https://img.olympics.com/images/image/private/t_16-9_640/f_auto/primary/fdky7ngqkdsgovshfyjn'),
    ('Escalada Deportiva', 'https://olympics.com/images/static/sports/pictograms/v2/clb.svg', 'https://img.olympics.com/images/image/private/t_s_pog_staticContent_hero_lg_2x/f_auto/primary/iz3n6ruqt299bnzhfeqz'),
    ('Esgrima', 'https://olympics.com/images/static/sports/pictograms/v2/fen.svg', 'https://img.olympics.com/images/image/private/t_s_pog_staticContent_hero_xl_2x/f_auto/v1668617476/primary/igr2r1cl1shgna5itint'),
    ('Fútbol', 'https://olympics.com/images/static/sports/pictograms/v2/fbl.svg', 'https://img.olympicchannel.com/images/image/private/t_16-9_1920/f_auto/primary/baa2nr7jo3wx6wv20vww'),
    ('Gimnasia Artística', 'https://olympics.com/images/static/sports/pictograms/v2/gac.svg', 'https://img.olympicchannel.com/images/image/private/t_16-9_1920/f_auto/primary/kurzlxstqem0gndjsdg6'),
    ('Gimnasia en Trampolín', 'https://olympics.com/images/static/sports/pictograms/v2/gtr.svg', 'https://img.olympics.com/images/image/private/t_social_share_thumb/f_auto/primary/kkbhon9bdnkbkuxmxedl'),
    ('Gimnasia Rítmica', 'https://olympics.com/images/static/sports/pictograms/v2/gry.svg', 'https://img2.rtve.es/v/16212454/square/?h=400'),
    ('Golf', 'https://olympics.com/images/static/sports/pictograms/v2/glf.svg', 'https://img.olympics.com/images/image/private/t_16-9_1280/f_auto/primary/ontnb9uedjdpobxdv2wq'),
    ('Halterofilia', 'https://olympics.com/images/static/sports/pictograms/v2/wlf.svg', 'https://img.olympics.com/images/image/private/t_social_share_thumb/f_auto/primary/xdas138kekdt45itaedj'),
    ('Hípica', 'https://olympics.com/images/static/sports/pictograms/v2/equ.svg', 'https://img.olympicchannel.com/images/image/private/t_16-9_1920/f_auto/primary/gcbsg3oj2brcu51v9cby'),
    ('Hockey sobre Césped', 'https://olympics.com/images/static/sports/pictograms/v2/hoc.svg', 'https://img.olympicchannel.com/images/image/private/t_16-9_1920/f_auto/primary/tm9btf3cbz1rzcosp8zq'),
    ('Judo', 'https://olympics.com/images/static/sports/pictograms/v2/jud.svg', 'https://img.olympicchannel.com/images/image/private/t_16-9_1920/f_auto/v1538355601/primary/t1aeramel0gscwsqfphp'),
    ('Lucha', 'https://olympics.com/images/static/sports/pictograms/v2/wre.svg', 'https://img.olympics.com/images/image/private/t_social_share_thumb/f_auto/primary/zpfcusht6yim4saswr0s'),
    ('Natación', 'https://olympics.com/images/static/sports/pictograms/v2/swm.svg', 'https://img.olympics.com/images/image/private/t_social_share_thumb/f_auto/primary/zs1xcpmpsmph7o88jzzy'),
    ('Natación Artística', 'https://olympics.com/images/static/sports/pictograms/v2/swa.svg', 'https://img.olympics.com/images/image/private/t_s_pog_staticContent_hero_xl_2x/f_auto/primary/nx4s17gtxfpg7qrstbiv'),
    ('Natación en aguas abiertas', 'https://olympics.com/images/static/sports/pictograms/v2/ows.svg', 'https://img.olympics.com/images/image/private/t_s_16_9_g_auto/t_s_w960/f_auto/primary/cyzhqqukwb5flvhmuzcl'),
    ('Pentatlón Moderno', 'https://olympics.com/images/static/sports/pictograms/v2/mpn.svg', 'https://img.olympicchannel.com/images/image/private/t_16-9_1920/f_auto/primary/za8wt8afawru6tcfwqoq'),
    ('Piragüismo en eslalon', 'https://olympics.com/images/static/sports/pictograms/v2/csl.svg', 'https://img.olympicchannel.com/images/image/private/t_16-9_1920/f_auto/primary/ikwft7ezkoufkb4ub90d'),
    ('Piragüismo en esprint', 'https://olympics.com/images/static/sports/pictograms/v2/csp.svg', 'https://img.olympics.com/images/image/private/t_s_pog_staticContent_hero_xl_2x/f_auto/primary/me0ehdnl33f6hqjph98l'),
    ('Remo', 'https://olympics.com/images/static/sports/pictograms/v2/row.svg', 'https://img.olympics.com/images/image/private/t_s_pog_staticContent_hero_xl_2x/f_auto/primary/e1gypbvpnxnxi3dr5o5p'),
    ('Rugby 7', 'https://olympics.com/images/static/sports/pictograms/v2/ru7.svg', 'https://img.olympics.com/images/image/private/t_social_share_thumb/f_auto/primary/sclk95yf832bdod8zczw'),
    ('Saltos', 'https://olympics.com/images/static/sports/pictograms/v2/div.svg', 'https://img.olympics.com/images/image/private/t_social_share_thumb/f_auto/primary/bdqvnnkze6xjdvpywbqs'),
    ('Skateboarding', 'https://olympics.com/images/static/sports/pictograms/v2/skb.svg', 'https://img.olympicchannel.com/images/image/private/t_16-9_1920/f_auto/primary/b47smaesg3uopzce5xru'),
    ('Surf', 'https://olympics.com/images/static/sports/pictograms/v2/srf.svg', 'https://img2.rtve.es/v/16202947/?w=1600'),
    ('Taekwondo', 'https://olympics.com/images/static/sports/pictograms/v2/tkw.svg', 'https://img.olympics.com/images/image/private/t_s_pog_staticContent_hero_xl_2x/f_auto/v1668614228/primary/ij1opbprknioaoxoqjmp'),
    ('Tenis', 'https://olympics.com/images/static/sports/pictograms/v2/ten.svg', 'https://img.olympics.com/images/image/private/t_s_pog_staticContent_hero_lg_2x/f_auto/primary/sopglarwc7wtqnlmf4hh'),
    ('Tenis de Mesa', 'https://olympics.com/images/static/sports/pictograms/v2/tte.svg', 'https://img.olympicchannel.com/images/image/private/t_16-9_1920/f_auto/primary/mkqvq9wzsos8owy5zsm7'),
    ('Tiro', 'https://olympics.com/images/static/sports/pictograms/v2/sho.svg', 'https://img.olympics.com/images/image/private/t_s_16_9_g_auto/t_s_w960/f_auto/v1712742587/primary/pos1mnwr5ukvwxxthbvv'),
    ('Tiro con Arco', 'https://olympics.com/images/static/sports/pictograms/v2/arc.svg', 'https://img.olympics.com/images/image/private/t_s_16_9_g_auto/t_s_w960/f_auto/primary/wxhrtu0jqbgxzjsyiinp'),
    ('Triatlón', 'https://olympics.com/images/static/sports/pictograms/v2/tri.svg', 'https://img.olympics.com/images/image/private/t_s_16_9_g_auto/t_s_w960/f_auto/primary/ptkcxz8iptbii39e4kug'),
    ('Vela', 'https://olympics.com/images/static/sports/pictograms/v2/sal.svg', 'https://img.olympics.com/images/image/private/t_s_pog_staticContent_hero_lg_2x/f_auto/primary/wrl4hfw1iydtrxv0osfu'),
    ('Voleibol', 'https://olympics.com/images/static/sports/pictograms/v2/vvo.svg', 'https://img.olympics.com/images/image/private/t_s_16_9_g_auto/t_s_w960/f_auto/primary/hi9x0n8pttlfk29ajnya'),
    ('Voleibol Playa', 'https://olympics.com/images/static/sports/pictograms/v2/vbv.svg', 'https://img.olympicchannel.com/images/image/private/t_16-9_1920/f_auto/primary/izcbaefoa5s2ilrfuygt'),
    ('Waterpolo', 'https://olympics.com/images/static/sports/pictograms/v2/wpo.svg', 'https://img.olympicchannel.com/images/image/private/t_16-9_1920/f_auto/primary/ceotnldil6umxksgrt20');
